import useCurrencyFormatter from "../../hooks/useCurrencyFormatter";
import useWealthSummary from "../../hooks/useWealthSummary";

const BALANCE_TOLERANCE =
  0.00000001;

type PerformanceItemProps = {
  label: string;
  value: string;
  description: string;
  valueClassName?: string;
};

const PerformanceItem = ({
  label,
  value,
  description,
  valueClassName =
    "text-slate-900",
}: PerformanceItemProps) => {
  return (
    <article className="rounded-xl border border-slate-200 bg-white p-4">
      <p className="text-xs font-medium text-slate-500">
        {label}
      </p>

      <p
        className={`mt-2 text-xl font-bold tabular-nums ${valueClassName}`}
      >
        {value}
      </p>

      <p className="mt-2 text-xs leading-5 text-slate-400">
        {description}
      </p>
    </article>
  );
};

const InvestmentPerformanceSummary =
  () => {
    const summary =
      useWealthSummary();

    const {
      formatCurrency,
      formatSignedCurrency,
    } = useCurrencyFormatter();

    const formatPerformance = (
      value: number | null,
    ) => {
      if (value === null) {
        return "FX pending";
      }

      if (
        Math.abs(value) <=
        BALANCE_TOLERANCE
      ) {
        return formatCurrency(0);
      }

      return formatSignedCurrency(
        value,
      );
    };

    const performanceClass = (
      value: number | null,
    ) => {
      if (
        value === null ||
        Math.abs(value) <=
          BALANCE_TOLERANCE
      ) {
        return "text-slate-900";
      }

      return value > 0
        ? "text-emerald-600"
        : "text-red-600";
    };

    const taxValue =
      summary.dividendTax === null
        ? "FX pending"
        : Math.abs(
              summary.dividendTax,
            ) <= BALANCE_TOLERANCE
          ? formatCurrency(0)
          : `-${formatCurrency(
              Math.abs(
                summary.dividendTax,
              ),
            )}`;

    return (
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div className="border-b border-slate-100 p-6">
          <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
            <div>
              <p className="text-sm font-medium text-slate-500">
                Investment performance
              </p>

              <h2 className="mt-1 text-xl font-semibold text-slate-900">
                Profit generated by
                your portfolio
              </h2>

              <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">
                Market gains, completed
                sales and dividend
                income are separated
                from money you
                contribute yourself.
              </p>
            </div>

            <div className="rounded-2xl bg-slate-50 px-5 py-4 lg:min-w-64">
              <p className="text-xs font-medium uppercase tracking-wide text-slate-500">
                Total investment profit
              </p>

              <p
                className={`mt-2 text-3xl font-bold tabular-nums ${performanceClass(
                  summary.totalInvestmentProfit,
                )}`}
              >
                {formatPerformance(
                  summary.totalInvestmentProfit,
                )}
              </p>

              <p className="mt-2 text-xs text-slate-400">
                Unrealized + realized
                + net dividends
              </p>
            </div>
          </div>
        </div>

        <div className="grid gap-4 bg-slate-50/40 p-5 md:grid-cols-3">
          <PerformanceItem
            label="Unrealized profit"
            value={formatPerformance(
              summary.investmentGainLoss,
            )}
            valueClassName={performanceClass(
              summary.investmentGainLoss,
            )}
            description="Profit or loss still inside positions you currently own."
          />

          <PerformanceItem
            label="Realized profit"
            value={formatPerformance(
              summary.realizedGainLoss,
            )}
            valueClassName={performanceClass(
              summary.realizedGainLoss,
            )}
            description={`${summary.realizedSaleCount} ${
              summary.realizedSaleCount ===
              1
                ? "sale"
                : "sales"
            } with realized performance recorded.`}
          />

          <PerformanceItem
            label="Net dividends"
            value={formatPerformance(
              summary.netDividends,
            )}
            valueClassName={performanceClass(
              summary.netDividends,
            )}
            description={`${summary.dividendPaymentCount} ${
              summary.dividendPaymentCount ===
              1
                ? "payment"
                : "payments"
            } after withholding tax.`}
          />
        </div>

        <div className="grid gap-4 border-t border-slate-100 p-5 sm:grid-cols-2">
          <div className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 px-4 py-4">
            <div>
              <p className="text-sm font-medium text-slate-700">
                Gross dividends
              </p>

              <p className="mt-1 text-xs text-slate-400">
                Before withholding tax
              </p>
            </div>

            <p className="text-lg font-bold text-slate-900 tabular-nums">
              {summary.grossDividends ===
              null
                ? "FX pending"
                : formatCurrency(
                    summary.grossDividends,
                  )}
            </p>
          </div>

          <div className="flex items-center justify-between gap-4 rounded-xl border border-slate-200 px-4 py-4">
            <div>
              <p className="text-sm font-medium text-slate-700">
                Dividend tax withheld
              </p>

              <p className="mt-1 text-xs text-slate-400">
                Tax deducted before
                cash receipt
              </p>
            </div>

            <p
              className={`text-lg font-bold tabular-nums ${
                summary.dividendTax !==
                  null &&
                summary.dividendTax >
                  BALANCE_TOLERANCE
                  ? "text-red-600"
                  : "text-slate-900"
              }`}
            >
              {taxValue}
            </p>
          </div>
        </div>
      </section>
    );
  };

export default InvestmentPerformanceSummary;

